### ISSUE TITLE
sub-space VF slicing crashes in v5.0, error in v4.0

### ISSUE THREAD

**Issue by cjdunn** [source-foundry/Slice#30]
- First I tried with Slice 5.0, installed via OSX dmg file, using Recursive VF 1.078
- Setting a single value for wght works to generate a static TTF, eg: 400
- I would expect that entering a range of values would work to slice a sub-space VF, eg: (300.0, 400.0) [300.0] 
but this results in a crash in version 5.0. In version 4.0 I get an error (see screenshot below) which says 
> Could not convert string to float: '(300.0, 400.0) [300.0]'

- I tried with 2 var fonts of my own with the same crashing result and DJR observed the same issue on his machine with v5.0 installed via homebrew, so I know the issue is not limited my set up or to the Recursive font

Thanks so much for your consideration, and for your work on this app, it looks very promising!

<img width="852" alt="Recursive_Slicing_error_for_sub-space_VF_(screenshot from version 4 0, version 5 0 just crashes)" src="https://user-images.githubusercontent.com/3900241/116291219-5636d600-a762-11eb-8472-5f45be16f723.png">

**Comment by chrissimpkins** [comment]
Thanks for the report! Unfortunately the functionality that you are looking for (gen a variable subset range of a full axis range) isn't supported in fonttool yet.  The options supported are static instances (every axis has a discrete location value) and "partial instantiation" with one or more axes fixed at a discrete value combined with one or more axes that have the *full axis range* from the source var font input.  There is interest in supporting these variable axis  "sub-ranges" but the source hasn't landed yet.  As soon as it does, I will make sure that it is available in this tool.  

Let's leave this open to track it.  

Thanks again!

**Comment by chrissimpkins** [comment]
Let me also see about adding editor entry validations and more helpful error messages.

**Comment by chrissimpkins** [comment]
We'll catch these exceptions as of 0828b12005b0ba119d1baaeffc102d15f922d4c9.  I added a validation to confirm that the axis editor data are appropriate with an informative error message when they are not.

<img width="425" alt="2021-04-27_19-07-20" src="https://user-images.githubusercontent.com/4249591/116323628-69f73200-a78c-11eb-8db7-57fca1335c3a.png">

Thank you very much for reporting this.  I'll push a new release with this fix.

**Comment by chrissimpkins** [comment]
The application crash bug reported here was fixed in v0.5.1.  The release is available.

**Comment by chrissimpkins** [comment]
I opened https://github.com/source-foundry/Slice/issues/31 to track the functionality that led to the discovery of this bug. I added a link to the fonttools issue where this is discussed. I seem to recall a more recent issue thread but can't locate it at the moment.  

Will close this issue as fixed.  Thank you very much for reporting this CJ. I really appreciate it!

**Comment by chrissimpkins** [comment]
Woot!  I stand corrected.  The L3 sub-range functionality is available in fonttools.  You can't change the *default* so it must be included in the sub-range, but it is currently possible to define sub-ranges.  I'll add this.   If you have thoughts about how we should support the range idiom in the editor, please let me know in https://github.com/source-foundry/Slice/issues/31

We could go with `100:300`, `(100, 300)`, `100..300`, etc.
