### ISSUE TITLE
Add WOFF and WOFF2 support

### ISSUE THREAD

**Issue by rik** [source-foundry/Slice#34]
I get the following error message: "No module named brotli".

Given the error message, I'm wondering if the fix would be to import fonttools with the woff extra.

**Comment by chrissimpkins** [comment]
Ah, tyvm!  Sorry, I've been testing on ttf builds only to date and missed the brotli import...  I'll fix this and prepare a new release.  Let's agree to call this feature expansion instead of a bug ;)

**Comment by chrissimpkins** [comment]
Reproduced and can confirm that the fix is to distribute the brotli package.  Will add zopfli too.  Next release will include woff and woff2 support.

**Comment by rik** [comment]
> Let's agree to call this feature expansion instead of a bug ;) 

Renamed the issue to reflect that 😂

**Comment by chrissimpkins** [comment]
> > Let's agree to call this feature expansion instead of a bug ;)
> 
> Renamed the issue to reflect that 😂

Haha! Tyvm

**Comment by chrissimpkins** [comment]
woff and woff2 font formats are supported as of v0.6.0.  Installers are available in our Releases and the homebrew update was pushed this evening.  

I came across an issue on Windows 10 where the OS seems to append a `.ttf` extension on the woff or woff2 extension when the file writes to disk.  Will open a bug report and troubleshoot this.  It isn't clear why it is happening at the moment.  Unit tests on Win suggest that we are building the appropriate format during the slicing process so, if you happen to be on Win, you should be able to simply remove the additional extension and are gtg.
