### ISSUE TITLE
System requirements for macOS dmg

### ISSUE THREAD

**Issue by jenskutilek** [source-foundry/Slice#40]
I downloaded the dmg for macOS just to find out that the App won't start on 10.13. I could not find this mentioned anywhere in the documentation pages. Would be nice to get an early warning ;)

---

@chrissimpkins Answer: Current repository releases require macOS 10.14 and above.  macOS install docs updated.  Users on macOS < 10.14 can build the app bundle with the instructions in https://github.com/source-foundry/Slice/issues/40#issuecomment-832644838.  Looking into a way to support earlier macOS versions in our releases.

**Comment by chrissimpkins** [comment]
Hmm.  Does not launch or do you get an error?

**Comment by jenskutilek** [comment]
Nothing happens when I try to launch the app. It doesn't have a crossed out icon like some apps that are unsupported on the current system.

... ah well, I tried to launch the app via Terminal, there I get an error message:

```
$ /Applications/Slice.app/Contents/MacOS/Slice
[3517] Error loading Python lib '/Applications/Slice.app/Contents/MacOS/Python': dlopen: dlopen(/Applications/Slice.app/Contents/MacOS/Python, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Slice.app/Contents/MacOS/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Slice.app/Contents/MacOS/libintl.8.dylib
```

**Comment by chrissimpkins** [comment]
I was just typing the following when you posted the above :)

I'm guessing that this is a PyInstaller related problem.  I compile the application in 10.15.7 and it is bw compatible with 10.14.  I don't have a 10.13 VM to test.

**Comment by chrissimpkins** [comment]
As I understand it, PyInstaller provides a forward compatibility guarantee, but not a backward compatibility guarantee across macOS (and other OS) versions.  

You can compile the app bundle yourself in a `requirements.txt` defined venv with:

```
make build-macos
```

https://github.com/source-foundry/Slice/blob/7a3f95d4ae59dd9f850235ddb4bda2a1695e1fef/Makefile#L36

Package will be located in the dist directory.

It would be *ideal* to move this entire process to build from GH Actions.  My understanding is that it doesn't support macOS < 10.15.  

Does Just's Font Goggles build work for you on 10.13?

**Comment by chrissimpkins** [comment]
Updated macOS installation docs with the 10.14+ requirement.  https://slice-gui.netlify.app/docs/install/#macos

Let me see if I can find a way to support earlier versions of macos.   Sorry for the troubles Jens.

**Comment by jenskutilek** [comment]
No worries! The latest release of FontGoggles (1.1.17) works for me.

I will try to build the app myself. I already was able to use the app via the `slicegui` pip installation.

**Comment by chrissimpkins** [comment]
Added #41 to support earlier versions of macOS

**Comment by chrissimpkins** [comment]
Added new docs on how to build the single file PyInstaller `Slice.app` macOS packages from source in https://slice-gui.netlify.app/docs/developer/#compile-app-distributions-by-platform
