### ISSUE TITLE
Question: is there a way to run Slice through command line?

### ISSUE THREAD

**Issue by aminabedi68** [source-foundry/Slice#57]
Hi
is there a way to run Slice through command line? i need to work with Slice as a part of build process.

**Comment by chrissimpkins** [comment]
There is not but it is straightforward to set up a build workflow with the same approach.  What do you need to do?

**Comment by aminabedi68** [comment]
I need to run Slice in the end of my build script, it would be great if i can run Slice through command line or python api. Unfortunately i can't explain further more right now but thank you for the answer.

**Comment by chrissimpkins** [comment]
Sure np.  Slice uses the fonttools library for the slicing functionality.
